<?php

namespace Sywise\QuizBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends EntityRepository
{

    public function countAllQuestions() {
        $count  = $this->createQueryBuilder('j')
            ->select('count(j.is)')
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function randomQuestion() {
        $q = $this->createQueryBuilder('e')
            ->orderBy('rand');
        return $q->getQuery()->getSingleResult();

    }

    public function findStartId() {
        return $this->$repository->find(20);
    }
}
