_welcome:
    path:     /
    defaults: { _controller: SywiseQuizBundle:Welcome:index }

sywise_quiz_homepage:
    path:     /hello/{name}
    defaults: { _controller: SywiseQuizBundle:Default:index, name: 'default  name' }

sywise_quiz_homepage_empty:
    path:     /hello/
    defaults: { _controller: SywiseQuizBundle:Default:index, name: 'default  name' }

sywise_create:
    path:     /create/
    defaults: { _controller: SywiseQuizBundle:Default:create}

sywise_add:
    path:     /add/
    defaults: { _controller: SywiseQuizBundle:Default:add}
    methods: [POST]

sywise_play:
    path:     /play/
    defaults: { _controller: SywiseQuizBundle:Play:index}

sywise_process:
    path:     /process/
    defaults: { _controller: SywiseQuizBundle:Play:process}
    methods: [POST]